version: '3'

services:
  docmost:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
      - redis
    environment:
      APP_URL: 'http://localhost:3000'
      APP_SECRET: '162191bb24b34f179ad00afdee1175d672ffe139259e3c3616b6c4eba82184bb'
      DATABASE_URL: 'postgresql://postgres:admin@db:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
    ports:
      - "3002:3002"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  docmost:
  db_data:
  redis_data:
