version: '3'

services:
  docmost:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/docmost?schema=public
    depends_on:
      - redis
    ports:
      - "3002:3002"
    extra_hosts:
      - "${POSTGRES_HOST}:host-gateway"
    restart: unless-stopped
    volumes:
      - ./docmost_data:/app/data/storage

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
