name: Deploy to VPS

on:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - dev

jobs:
  my_job:
    name: deploy to vps
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            
      - name: Run docker-compose on VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
          "cd ${{ secrets.VPS_DEPLOY_PATH }} && docker-compose down && git pull && docker-compose up -d"
