on:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - dev

jobs:
  my_job:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.VPS_DEPLOY_PATH }}
            docker-compose down
            git pull
            docker-compose up -d
